// Widget tests for AutoGeneratedHeadersSection — the read-only list under the
// HEADERS editor showing what the client adds at send time: first-frame rows
// for a fresh request, ADD copies an overridable row into the editable
// headers (re-enabling a disabled same-name row), the collapse toggle, the
// implied Content-Type for a config lacking the row, and nothing for
// non-HTTP kinds.

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:getman/core/domain/entities/body_type.dart';
import 'package:getman/core/domain/entities/request_config_entity.dart';
import 'package:getman/core/network/auto_generated_headers.dart';
import 'package:getman/core/network/request_kind.dart';
import 'package:getman/core/theme/themes/brutalist/brutalist_theme.dart';
import 'package:getman/features/tabs/domain/entities/panel_entity.dart';
import 'package:getman/features/tabs/domain/entities/request_tab_entity.dart';
import 'package:getman/features/tabs/domain/repositories/tabs_repository.dart';
import 'package:getman/features/tabs/domain/usecases/send_request_use_case.dart';
import 'package:getman/features/tabs/presentation/bloc/tabs_bloc.dart';
import 'package:getman/features/tabs/presentation/bloc/tabs_event.dart';
import 'package:getman/features/tabs/presentation/widgets/auto_generated_headers_section.dart';
import 'package:mocktail/mocktail.dart';

class _MockTabsRepository extends Mock implements TabsRepository {}

class _MockSendRequestUseCase extends Mock implements SendRequestUseCase {}

class _FakeConfig extends Fake implements HttpRequestConfigEntity {}

class _FakePanel extends Fake implements PanelEntity {}

void main() {
  late _MockTabsRepository repository;

  setUpAll(() {
    registerFallbackValue(_FakeConfig());
    registerFallbackValue(_FakePanel());
    registerFallbackValue(
      const HttpRequestTabEntity(
        tabId: 'fallback',
        config: HttpRequestConfigEntity(id: 'fallback'),
      ),
    );
  });

  setUp(() {
    repository = _MockTabsRepository();
    when(() => repository.saveTabs(any())).thenAnswer((_) async {});
    when(() => repository.putTab(any())).thenAnswer((_) async {});
    when(() => repository.deleteTabs(any())).thenAnswer((_) async {});
    when(() => repository.saveTabOrder(any())).thenAnswer((_) async {});
    when(() => repository.putPanel(any())).thenAnswer((_) async {});
    when(() => repository.deletePanels(any())).thenAnswer((_) async {});
    when(
      () => repository.savePanelMeta(any(), any()),
    ).thenAnswer((_) async {});
  });

  Future<TabsBloc> pump(
    WidgetTester tester,
    HttpRequestConfigEntity config,
  ) async {
    final tab = HttpRequestTabEntity(tabId: 't', config: config);
    when(() => repository.getPanels()).thenAnswer(
      (_) async => [
        PanelEntity(id: 'p1', name: 'Panel 1', tabs: [tab], activeTabId: 't'),
      ],
    );
    when(() => repository.getActivePanelId()).thenAnswer((_) async => 'p1');
    final bloc = TabsBloc(
      repository: repository,
      sendRequestUseCase: _MockSendRequestUseCase(),
    )..add(const LoadTabs());
    await bloc.stream.firstWhere((s) => !s.isLoading && s.tabs.isNotEmpty);
    addTearDown(bloc.close);
    await tester.pumpWidget(
      MaterialApp(
        theme: brutalistTheme(Brightness.light),
        home: Scaffold(
          body: BlocProvider.value(
            value: bloc,
            child: const AutoGeneratedHeadersSection(tabId: 't'),
          ),
        ),
      ),
    );
    await tester.pump();
    return bloc;
  }

  HttpRequestConfigEntity config(TabsBloc bloc) =>
      bloc.state.tabs.byId('t')!.config;

  testWidgets('first frame lists the client-added rows for a fresh request', (
    tester,
  ) async {
    await pump(tester, const HttpRequestConfigEntity(id: 't'));
    expect(find.text('AUTO-GENERATED HEADERS (3)'), findsOneWidget);
    expect(find.byKey(const ValueKey('auto_header_Host')), findsOneWidget);
    expect(
      find.byKey(const ValueKey('auto_header_User-Agent')),
      findsOneWidget,
    );
    expect(
      find.byKey(const ValueKey('auto_header_Accept-Encoding')),
      findsOneWidget,
    );
    expect(find.text(kCalculatedWhenSent), findsOneWidget);
    expect(find.text('gzip'), findsOneWidget);
    expect(find.textContaining('Dart/'), findsOneWidget);
  });

  testWidgets('only overridable rows offer ADD', (tester) async {
    await pump(tester, const HttpRequestConfigEntity(id: 't'));
    expect(
      find.byKey(const ValueKey('auto_header_add_Accept-Encoding')),
      findsOneWidget,
    );
    expect(
      find.byKey(const ValueKey('auto_header_add_User-Agent')),
      findsOneWidget,
    );
    expect(find.byKey(const ValueKey('auto_header_add_Host')), findsNothing);
  });

  testWidgets('ADD copies the row into the editable headers and hides it', (
    tester,
  ) async {
    final bloc = await pump(tester, const HttpRequestConfigEntity(id: 't'));
    await tester.tap(
      find.byKey(const ValueKey('auto_header_add_Accept-Encoding')),
    );
    await tester.pumpAndSettle();
    expect(config(bloc).headers['Accept-Encoding'], 'gzip');
    expect(config(bloc).headers.keys.last, 'Accept-Encoding');
    expect(
      find.byKey(const ValueKey('auto_header_Accept-Encoding')),
      findsNothing,
    );
    expect(find.text('AUTO-GENERATED HEADERS (2)'), findsOneWidget);
    await tester.pump(const Duration(seconds: 11)); // flush debounced save
  });

  testWidgets('the label row collapses the list and expands it again', (
    tester,
  ) async {
    await pump(tester, const HttpRequestConfigEntity(id: 't'));
    await tester.tap(find.byKey(const ValueKey('auto_headers_toggle')));
    await tester.pumpAndSettle();
    expect(find.byKey(const ValueKey('auto_header_Host')), findsNothing);
    expect(find.text('AUTO-GENERATED HEADERS (3)'), findsOneWidget);
    await tester.tap(find.byKey(const ValueKey('auto_headers_toggle')));
    await tester.pumpAndSettle();
    expect(find.byKey(const ValueKey('auto_header_Host')), findsOneWidget);
  });

  testWidgets('a request lacking a Content-Type row shows the implied one', (
    tester,
  ) async {
    await pump(
      tester,
      const HttpRequestConfigEntity(id: 't', headers: {}, body: '{}'),
    );
    expect(find.text('AUTO-GENERATED HEADERS (5)'), findsOneWidget);
    expect(
      find.byKey(const ValueKey('auto_header_Content-Type')),
      findsOneWidget,
    );
    expect(find.text('application/json'), findsOneWidget);
    expect(
      find.byKey(const ValueKey('auto_header_Content-Length')),
      findsOneWidget,
    );
  });

  testWidgets(
    'ADD on a disabled same-name row re-enables it with the wire value',
    (
      tester,
    ) async {
      final bloc = await pump(
        tester,
        const HttpRequestConfigEntity(
          id: 't',
          bodyType: BodyType.urlencoded,
          disabledHeaderKeys: {'Content-Type'},
        ),
      );
      expect(find.text('application/x-www-form-urlencoded'), findsOneWidget);
      await tester.tap(
        find.byKey(const ValueKey('auto_header_add_Content-Type')),
      );
      await tester.pumpAndSettle();
      expect(
        config(bloc).headers['Content-Type'],
        'application/x-www-form-urlencoded',
      );
      expect(config(bloc).disabledHeaderKeys, isEmpty);
      expect(config(bloc).headers.keys.toList(), ['Content-Type', 'Accept']);
      await tester.pump(const Duration(seconds: 11)); // flush debounced save
    },
  );

  testWidgets('renders nothing for non-HTTP kinds', (tester) async {
    await pump(
      tester,
      const HttpRequestConfigEntity(id: 't', kind: RequestKind.sse),
    );
    expect(find.textContaining('AUTO-GENERATED'), findsNothing);
  });
}
