// AutoGeneratedHeadersSection: the read-only "AUTO-GENERATED HEADERS (N)"
// list under the HEADERS editor (Postman-style) showing what the HTTP client
// adds at send time on top of the editable rows — implied Content-Type,
// Content-Length/Host placeholders, dart:io's User-Agent + Accept-Encoding,
// the AUTH tab's header. Rows come from autoGeneratedHeaders() (pure,
// core/network); this widget only renders them. Overridable rows carry an
// ADD button that copies the row into the editable headers (re-enabling a
// disabled same-name row), after which the auto row disappears because an
// explicit enabled row now covers it. Collapsible (ephemeral, like the
// bulk toggle); renders nothing when the list is empty (WS/SSE kinds).
// Composed by HeadersTabView.
import 'package:collection/collection.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:getman/core/network/auto_generated_headers.dart';
import 'package:getman/core/network/default_user_agent.dart';
import 'package:getman/core/theme/app_theme.dart';
import 'package:getman/features/tabs/domain/entities/request_tab_entity.dart';
import 'package:getman/features/tabs/presentation/bloc/tabs_bloc.dart';
import 'package:getman/features/tabs/presentation/bloc/tabs_event.dart';
import 'package:getman/features/tabs/presentation/bloc/tabs_state.dart';

const ListEquality<AutoGeneratedHeader> _rowsEquality =
    ListEquality<AutoGeneratedHeader>();

/// Read-only list of the headers the client adds when the request is sent.
class AutoGeneratedHeadersSection extends StatefulWidget {
  const AutoGeneratedHeadersSection({required this.tabId, super.key});
  final String tabId;

  @override
  State<AutoGeneratedHeadersSection> createState() =>
      _AutoGeneratedHeadersSectionState();
}

class _AutoGeneratedHeadersSectionState
    extends State<AutoGeneratedHeadersSection> {
  // Ephemeral view preference: not persisted, resets to expanded on reload.
  bool _expanded = true;
  // dart:io's default (null on web) — resolved once per widget instance.
  final String? _userAgent = defaultUserAgent();

  List<AutoGeneratedHeader> _rows(TabsState state) {
    final tab = state.tabs.byId(widget.tabId);
    if (tab == null) return const [];
    return autoGeneratedHeaders(tab.config, userAgent: _userAgent);
  }

  void _addRow(BuildContext context, AutoGeneratedHeader row) {
    final bloc = context.read<TabsBloc>();
    final tab = bloc.state.tabs.byId(widget.tabId);
    if (tab == null) return;
    final headers = Map<String, String>.of(tab.config.headers);
    // A disabled same-name row (any casing) is re-enabled in place rather
    // than duplicated under a second spelling.
    final key =
        headers.keys.firstWhereOrNull(
          (k) => k.toLowerCase() == row.name.toLowerCase(),
        ) ??
        row.name;
    headers[key] = row.overrideValue;
    bloc.add(
      UpdateTab(
        tab.copyWith(
          config: tab.config.copyWith(
            headers: headers,
            disabledHeaderKeys: {
              for (final k in tab.config.disabledHeaderKeys)
                if (k != key) k,
            },
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<TabsBloc, TabsState>(
      buildWhen: (prev, next) =>
          !_rowsEquality.equals(_rows(prev), _rows(next)),
      builder: (context, state) {
        final rows = _rows(state);
        if (rows.isEmpty) return const SizedBox.shrink();
        final theme = Theme.of(context);
        final layout = context.appLayout;
        final typography = context.appTypography;
        final muted = theme.colorScheme.onSurface.withValues(alpha: 0.6);
        return DecoratedBox(
          decoration: BoxDecoration(
            border: Border(
              top: BorderSide(
                color: theme.dividerColor,
                width: layout.borderThin,
              ),
            ),
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              context.appDecoration.wrapInteractive(
                onTap: () => setState(() => _expanded = !_expanded),
                child: Padding(
                  key: const ValueKey('auto_headers_toggle'),
                  padding: EdgeInsets.symmetric(
                    horizontal: layout.pagePadding,
                    vertical: layout.badgePaddingVertical,
                  ),
                  child: Row(
                    children: [
                      Icon(
                        _expanded ? Icons.expand_more : Icons.chevron_right,
                        size: layout.smallIconSize,
                        color: theme.colorScheme.secondary,
                      ),
                      SizedBox(width: layout.tabSpacing),
                      Text(
                        'AUTO-GENERATED HEADERS (${rows.length})',
                        style: TextStyle(
                          fontSize: layout.fontSizeSmall,
                          fontWeight: typography.titleWeight,
                          color: theme.colorScheme.onSurface,
                        ),
                      ),
                      SizedBox(width: layout.tabSpacing),
                      Tooltip(
                        message:
                            'Added by the HTTP client when the request is '
                            'sent. Add a header with the same name to '
                            'override one.',
                        child: Icon(
                          Icons.info_outline,
                          size: layout.smallIconSize,
                          color: muted,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              if (_expanded)
                for (final row in rows)
                  _AutoGeneratedHeaderRow(
                    row: row,
                    muted: muted,
                    onAdd: row.canOverride ? () => _addRow(context, row) : null,
                  ),
            ],
          ),
        );
      },
    );
  }
}

class _AutoGeneratedHeaderRow extends StatelessWidget {
  const _AutoGeneratedHeaderRow({
    required this.row,
    required this.muted,
    required this.onAdd,
  });
  final AutoGeneratedHeader row;
  final Color muted;
  final VoidCallback? onAdd;

  @override
  Widget build(BuildContext context) {
    final layout = context.appLayout;
    final typography = context.appTypography;
    final add = onAdd;
    return Padding(
      key: ValueKey('auto_header_${row.name}'),
      padding: EdgeInsets.symmetric(horizontal: layout.pagePadding),
      child: Row(
        children: [
          Expanded(
            flex: 2,
            child: Text(
              row.name,
              overflow: TextOverflow.ellipsis,
              style: TextStyle(
                fontSize: layout.fontSizeSmall,
                fontWeight: typography.titleWeight,
                color: muted,
              ),
            ),
          ),
          SizedBox(width: layout.tabSpacing),
          Expanded(
            flex: 3,
            child: Text(
              row.value,
              overflow: TextOverflow.ellipsis,
              style: TextStyle(
                fontSize: layout.fontSizeSmall,
                fontFamily: typography.codeFontFamily,
                color: muted,
              ),
            ),
          ),
          // Fixed trailing slot keeps values aligned whether or not a row
          // offers ADD.
          SizedBox(
            width: layout.kvToggleSlotWidth,
            height: layout.kvToggleSlotWidth,
            child: add == null
                ? null
                : context.appDecoration.wrapInteractive(
                    child: IconButton(
                      key: ValueKey('auto_header_add_${row.name}'),
                      icon: Icon(Icons.add, size: layout.smallIconSize),
                      tooltip: 'Add as editable header',
                      padding: EdgeInsets.zero,
                      onPressed: add,
                    ),
                  ),
          ),
        ],
      ),
    );
  }
}
