// autoGeneratedHeaders(): the read-only "auto-generated headers" rows the
// HEADERS tab lists under the editable ones — everything the HTTP client puts
// on the wire that isn't an explicit enabled row: the Content-Type the body
// type implies (BodyTypeUtils), the Content-Length/Host placeholders dart:io
// computes at send, dart:io's default User-Agent + `Accept-Encoding: gzip`,
// and the header the AUTH tab generates (value masked — never the secret).
// Postman shows the same list; a user overrides a row by adding an explicit
// header with the same name (canOverride marks the rows where that makes
// sense). Pure — dart:io-free; the runtime User-Agent is injected by the
// caller via default_user_agent.dart so this stays testable and web-safe.
//
// Gotchas: an explicit row only hides an auto row while it's ENABLED — a
// disabled Content-Type row still leaves the body-type default on the wire
// (RequestSerializer forces it), so the list keeps showing it. An empty raw
// body sends no data, so it gets neither Content-Type nor Content-Length
// (mirrors Dio, which implies nothing for a null body).

import 'package:equatable/equatable.dart';
import 'package:getman/core/domain/auth_application.dart';
import 'package:getman/core/domain/entities/body_type.dart';
import 'package:getman/core/domain/entities/request_config_entity.dart';
import 'package:getman/core/network/request_kind.dart';
import 'package:getman/core/utils/body_type_utils.dart';
import 'package:getman/core/utils/header_utils.dart';

/// Placeholder value for headers the client computes per send (Host,
/// Content-Length, the multipart boundary).
const String kCalculatedWhenSent = '<calculated when request is sent>';

/// Placeholder value for the header the AUTH tab generates — the credential
/// itself is never shown here.
const String kGeneratedFromAuthTab = '<generated from the AUTH tab>';

/// One read-only row of the HEADERS tab's auto-generated list.
class AutoGeneratedHeader extends Equatable {
  const AutoGeneratedHeader({
    required this.name,
    required this.value,
    this.canOverride = false,
    String? overrideValue,
  }) : overrideValue = overrideValue ?? value;

  final String name;

  /// What the wire will carry, for display (may embed a placeholder such as
  /// the multipart boundary).
  final String value;

  /// The value an explicit editable row gets when the user overrides this
  /// row — [value] minus any per-send placeholder.
  final String overrideValue;

  /// True when adding an explicit editable row with this name/value is a
  /// sensible way to change it (Content-Type, User-Agent, Accept-Encoding) —
  /// false for per-send computed values and the AUTH tab's header.
  final bool canOverride;

  @override
  List<Object?> get props => [name, value, canOverride, overrideValue];
}

/// The headers the client adds on top of [config]'s enabled rows when the
/// request is sent, in wire-ish order. [userAgent] is dart:io's default
/// (see `defaultUserAgent()`); null (web) omits the row. Empty for non-HTTP
/// kinds (WebSocket/SSE/MCP handshakes carry their own protocol headers).
List<AutoGeneratedHeader> autoGeneratedHeaders(
  HttpRequestConfigEntity config, {
  required String? userAgent,
}) {
  if (config.kind != RequestKind.http) return const [];
  final enabled = config.enabledHeaders;
  bool has(String name) => HeaderUtils.hasHeader(enabled, name);

  final rows = <AutoGeneratedHeader>[];
  final sendsBody =
      config.bodyType != BodyType.none &&
      !(config.bodyType == BodyType.raw && config.body.isEmpty);
  if (sendsBody) {
    if (!has(BodyTypeUtils.contentTypeHeader)) {
      final type = BodyTypeUtils.defaultContentType(config.bodyType)!;
      rows.add(
        AutoGeneratedHeader(
          name: BodyTypeUtils.contentTypeHeader,
          value: config.bodyType == BodyType.multipart
              ? '$type; boundary=$kCalculatedWhenSent'
              : type,
          canOverride: true,
          overrideValue: type,
        ),
      );
    }
    rows.add(
      const AutoGeneratedHeader(
        name: 'Content-Length',
        value: kCalculatedWhenSent,
      ),
    );
  }
  rows.add(const AutoGeneratedHeader(name: 'Host', value: kCalculatedWhenSent));
  if (userAgent != null && !has('User-Agent')) {
    rows.add(
      AutoGeneratedHeader(
        name: 'User-Agent',
        value: userAgent,
        canOverride: true,
      ),
    );
  }
  if (!has('Accept-Encoding')) {
    rows.add(
      const AutoGeneratedHeader(
        name: 'Accept-Encoding',
        value: 'gzip',
        canOverride: true,
      ),
    );
  }
  // Same skip-if-set decision as the send path; identity resolver so an
  // unresolved `{{token}}` still counts as "will be sent".
  final auth = resolveAuthApplication(
    auth: config.authConfig,
    currentHeaders: enabled,
    resolve: (v) => v,
    hasQueryParam: (_) => false,
  );
  for (final name in auth.headers.keys) {
    rows.add(AutoGeneratedHeader(name: name, value: kGeneratedFromAuthTab));
  }
  return rows;
}
