// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:getman/features/chaining/data/models/assertion_model.dart';
import 'package:getman/features/chaining/data/models/extraction_rule_model.dart';
import 'package:getman/features/chaining/data/models/request_rules_model.dart';
import 'package:getman/features/collections/data/models/collection_node_model.dart';
import 'package:getman/features/collections/data/models/saved_example_model.dart';
import 'package:getman/features/cookies/data/models/stored_cookie_model.dart';
import 'package:getman/features/environments/data/models/environment_model.dart';
import 'package:getman/features/history/data/models/request_config_model.dart';
import 'package:getman/features/settings/data/models/settings_model.dart';
import 'package:getman/features/tabs/data/models/multipart_field_model.dart';
import 'package:getman/features/tabs/data/models/request_tab_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AssertionModelAdapter());
    registerAdapter(CollectionNodeAdapter());
    registerAdapter(EnvironmentModelAdapter());
    registerAdapter(ExtractionRuleModelAdapter());
    registerAdapter(HttpRequestConfigAdapter());
    registerAdapter(HttpRequestTabModelAdapter());
    registerAdapter(MultipartFieldModelAdapter());
    registerAdapter(RequestRulesModelAdapter());
    registerAdapter(SavedExampleModelAdapter());
    registerAdapter(SettingsModelAdapter());
    registerAdapter(StoredCookieModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AssertionModelAdapter());
    registerAdapter(CollectionNodeAdapter());
    registerAdapter(EnvironmentModelAdapter());
    registerAdapter(ExtractionRuleModelAdapter());
    registerAdapter(HttpRequestConfigAdapter());
    registerAdapter(HttpRequestTabModelAdapter());
    registerAdapter(MultipartFieldModelAdapter());
    registerAdapter(RequestRulesModelAdapter());
    registerAdapter(SavedExampleModelAdapter());
    registerAdapter(SettingsModelAdapter());
    registerAdapter(StoredCookieModelAdapter());
  }
}
