// Unit tests for autoGeneratedHeaders(): the read-only rows the HEADERS tab
// lists for what the HTTP client adds on top of the editable headers — the
// implied Content-Type, Content-Length/Host placeholders, dart:io's
// User-Agent + Accept-Encoding defaults, and the AUTH tab's header — each
// hidden when an explicit enabled row already covers it.

import 'package:flutter_test/flutter_test.dart';
import 'package:getman/core/domain/entities/auth_config.dart';
import 'package:getman/core/domain/entities/body_type.dart';
import 'package:getman/core/domain/entities/request_config_entity.dart';
import 'package:getman/core/network/auto_generated_headers.dart';
import 'package:getman/core/network/request_kind.dart';

void main() {
  const ua = 'Dart/3.9 (dart:io)';
  List<String> names(HttpRequestConfigEntity c, {String? userAgent = ua}) =>
      autoGeneratedHeaders(c, userAgent: userAgent).map((h) => h.name).toList();
  AutoGeneratedHeader? row(
    HttpRequestConfigEntity c,
    String name, {
    String? userAgent = ua,
  }) {
    for (final h in autoGeneratedHeaders(c, userAgent: userAgent)) {
      if (h.name == name) return h;
    }
    return null;
  }

  group('autoGeneratedHeaders', () {
    test('a fresh GET lists Host, User-Agent and Accept-Encoding only', () {
      const c = HttpRequestConfigEntity(id: 'x');
      expect(names(c), ['Host', 'User-Agent', 'Accept-Encoding']);
      expect(row(c, 'Host')!.value, kCalculatedWhenSent);
      expect(row(c, 'Host')!.canOverride, isFalse);
      expect(row(c, 'User-Agent')!.value, ua);
      expect(row(c, 'User-Agent')!.canOverride, isTrue);
      expect(row(c, 'Accept-Encoding')!.value, 'gzip');
      expect(row(c, 'Accept-Encoding')!.canOverride, isTrue);
    });

    test(
      'a raw body with the default Content-Type row adds Content-Length',
      () {
        const c = HttpRequestConfigEntity(id: 'x', body: '{"a":1}');
        expect(names(c), [
          'Content-Length',
          'Host',
          'User-Agent',
          'Accept-Encoding',
        ]);
        expect(row(c, 'Content-Length')!.value, kCalculatedWhenSent);
        expect(row(c, 'Content-Length')!.canOverride, isFalse);
      },
    );

    test('a raw body with no Content-Type row shows the implied json', () {
      const c = HttpRequestConfigEntity(id: 'x', headers: {}, body: '{}');
      expect(
        autoGeneratedHeaders(c, userAgent: ua).first,
        const AutoGeneratedHeader(
          name: 'Content-Type',
          value: 'application/json',
          canOverride: true,
        ),
      );
    });

    test('an EMPTY raw body sends nothing: no Content-Type/Length rows', () {
      const c = HttpRequestConfigEntity(id: 'x', headers: {});
      expect(names(c), ['Host', 'User-Agent', 'Accept-Encoding']);
    });

    test('multipart with no row shows the boundary placeholder', () {
      const c = HttpRequestConfigEntity(
        id: 'x',
        headers: {},
        bodyType: BodyType.multipart,
      );
      expect(
        row(c, 'Content-Type')!.value,
        'multipart/form-data; boundary=$kCalculatedWhenSent',
      );
    });

    test('a DISABLED Content-Type row counts as absent', () {
      const c = HttpRequestConfigEntity(
        id: 'x',
        bodyType: BodyType.urlencoded,
        disabledHeaderKeys: {'Content-Type'},
      );
      expect(
        row(c, 'Content-Type')!.value,
        'application/x-www-form-urlencoded',
      );
    });

    test(
      'explicit enabled Accept-Encoding / User-Agent rows hide the auto ones',
      () {
        const c = HttpRequestConfigEntity(
          id: 'x',
          headers: {'accept-encoding': 'identity', 'User-Agent': 'me/1.0'},
        );
        expect(names(c), ['Host']);
      },
    );

    test('no runtime user agent (web) hides the User-Agent row', () {
      const c = HttpRequestConfigEntity(id: 'x');
      expect(names(c, userAgent: null), ['Host', 'Accept-Encoding']);
    });

    test('bearer auth lists Authorization as generated from the AUTH tab', () {
      final c = HttpRequestConfigEntity(
        id: 'x',
        auth: const AuthConfig(type: AuthType.bearer, token: '{{t}}').toMap(),
      );
      expect(names(c).last, 'Authorization');
      expect(row(c, 'Authorization')!.value, kGeneratedFromAuthTab);
      expect(row(c, 'Authorization')!.canOverride, isFalse);
    });

    test('an explicit Authorization row, or an empty token, hides it', () {
      final explicit = HttpRequestConfigEntity(
        id: 'x',
        headers: const {'Authorization': 'Bearer abc'},
        auth: const AuthConfig(type: AuthType.bearer, token: 't').toMap(),
      );
      expect(row(explicit, 'Authorization'), isNull);
      final empty = HttpRequestConfigEntity(
        id: 'x',
        auth: const AuthConfig(type: AuthType.bearer).toMap(),
      );
      expect(row(empty, 'Authorization'), isNull);
    });

    test(
      'api-key auth uses the key name in header mode, nothing in query mode',
      () {
        final header = HttpRequestConfigEntity(
          id: 'x',
          auth: const AuthConfig(
            type: AuthType.apiKey,
            apiKeyName: 'X-Api-Key',
            apiKeyValue: 'v',
          ).toMap(),
        );
        expect(row(header, 'X-Api-Key')!.value, kGeneratedFromAuthTab);
        final query = HttpRequestConfigEntity(
          id: 'x',
          auth: const AuthConfig(
            type: AuthType.apiKey,
            apiKeyName: 'key',
            apiKeyValue: 'v',
            apiKeyLocation: ApiKeyLocation.query,
          ).toMap(),
        );
        expect(names(query), ['Host', 'User-Agent', 'Accept-Encoding']);
      },
    );

    test('non-HTTP kinds list nothing', () {
      const c = HttpRequestConfigEntity(id: 'x', kind: RequestKind.sse);
      expect(autoGeneratedHeaders(c, userAgent: ua), isEmpty);
    });

    test('rows are value-equal; overrideValue defaults to value', () {
      const a = AutoGeneratedHeader(name: 'Host', value: 'h');
      const b = AutoGeneratedHeader(name: 'Host', value: 'h');
      expect(a, b);
      expect(a.overrideValue, 'h');
      expect(a.props, ['Host', 'h', false, 'h']);
    });

    test('the multipart row overrides to the boundary-less type', () {
      const c = HttpRequestConfigEntity(
        id: 'x',
        headers: {},
        bodyType: BodyType.multipart,
      );
      expect(row(c, 'Content-Type')!.overrideValue, 'multipart/form-data');
    });
  });
}
